import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import ResumonBadge from "./_components/resumon-badge";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "flex min-h-svh flex-col bg-[rgb(20,20,20)]",
          GeistSans.className,
        )}
      >
        <TRPCReactProvider>
          <div className="">{children}</div>
          <ResumonBadge />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
