import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import ResumonBadge from "./_components/resumon-badge";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={cn("flex min-h-svh flex-col", GeistSans.className)}>
        <TRPCReactProvider>
          <div className="">{children}</div>
          <ResumonBadge />
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
